name: Deploy Lambda to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Upload & Deploy Lambda
    runs-on: ubuntu-latest

    env:
      AWS_REGION: eu-north-1
      FUNCTION_NAME: ContactFormHandler
      S3_BUCKET: serverless-contact-lambda-code
      S3_KEY: lambda.zip

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Zip Lambda Function
        run: |
          cd lambda
          zip -r ../lambda.zip .

      - name: Upload Lambda to S3
        run: |
          aws s3 cp lambda.zip s3://$S3_BUCKET/$S3_KEY
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AKIAQLVQRA2HX2I5MLEV }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.qmSxZNQOwheSwXJjjtYPa6MvgJvryhXu/Qxt/k4S }}
          AWS_DEFAULT_REGION: ${{ env.eu-north-1 }}

      - name: Update Lambda Code
        run: |
          aws lambda update-function-code \
            --function-name $FUNCTION_NAME \
            --s3-bucket $S3_BUCKET \
            --s3-key $S3_KEY
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AKIAQLVQRA2HX2I5MLEV }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.qmSxZNQOwheSwXJjjtYPa6MvgJvryhXu/Qxt/k4S}}
          AWS_DEFAULT_REGION: ${{ env.eu-north-1 }}
